name: first-workflow
on: [push]

jobs:
  shell-cmd-job:
    runs-on: ubuntu-latest # 실습 편의를 위해 latest를 사용하는 것일 뿐, 라이브 환경에서는 절대 사용하지 마셈!
    steps:
      - name: echo Hello
        run: echo "Hello World"
      - name: multiple line cmd
        run: | # YAML 파일에서 |(Pipe) 뒤에서는 개행(\n)을 모두 받아들인다.
          node -v
          npm -v